### ISSUE TITLE
pyinit() & exact fits

### ISSUE THREAD

**Issue by msalibian** [msalibian/RobStatTM#3] opened 2019-05-28 21:30 UTC
When the data lie on a perfect line, pyinit::pyinit() seems to have problems. Results don't seem right. In this example, the data is on the line y = x + 100, but the pyinit() candidates look off:
```r
y <- 101:200
x <- 1:100
X <- cbind(rep(1,100), x)
control <- RobStatTM::lmrobdet.control()
n <- nrow(X)
p <- ncol(X)
dee <- control$bb
a1 <- pyinit::pyinit(x=X, y=y, intercept=FALSE, delta=dee,
                    cc=1.54764,
                    psc_keep=control$psc_keep*(1-(p/n)), resid_keep_method=control$resid_keep_method,
                    resid_keep_thresh = control$resid_keep_thresh, resid_keep_prop=control$resid_keep_prop,
                    maxit = control$py_maxit, eps=control$py_eps,
                    mscale_maxit = control$mscale_maxit, mscale_tol = control$mscale_tol,
                    mscale_rho_fun="bisquare")
```
produces
```
> a1
$coefficients
             [,1] [,2]
[1,] 0.0001154071  100
[2,] 1.0000000000    1

$objective
[1] 1.797693e+308           NaN
```

**Comment by dakep** [comment] 2019-08-02 22:57
The issue is fixed in pyinit version 1.0.3.

**Closed as completed** 2019-08-03 16:21 UTC
