### ISSUE TITLE
lmrobLinTest bug and new anova.lmrob

### ISSUE THREAD

**Issue by harrysouthworth** [msalibian/RobStatTM#4] opened 2020-10-07 12:03 UTC
robustbase::anova.lmrob has been broken since at least 2014 and the bug report hasn't been addressed. Since RobStatTM has lmrobLinTest, I decided to use that instead, but found that it doesn't work because object$control$family doesn't exist. 

I think the fix is to swap object$control$family to object$control$psi.

I wrote a simple wrapper, below, to generalize lmrobLinTest to more than 2 models, do a couple more sanity tests on the inputs, and make the output a bit more like what other anova functions output. 

This should probably be a pull request but I can't build the package at my end due to some roxygen bug that I don't understand, so thought it would be quicker to do it like this. Because I couldn't build it, the roxygen below hasn't been tested but I'm pretty sure the @method and @export lines are correct.

#' Robust analysis of variance type tests.
#' @param object,... Robust linear models fit by \code{robustbase::lmrob}.
#' @details Contrary to other \code{anova} functions, the first object must
#'   be the model with the most terms. The results are returned in the more
#'   usual way, the simplest model being on the first row. The results of the
#'   robust F-test and robust chi-squared test are both returned. The second
#'   of these should, generally, be preferred. The function is a simple
#'   wrapper to \link{\code{lmrobLinTest}}.
#' @method anova lmrob
#' @export
anova.lmrob <- function(object, ...){
  o <- list(object, ...)
  res <- list()

  for (i in 2:length(o)){
    res[[i - 1]] <- lmrobLinTest(o[[i - 1]], o[[i]])
  }
  res[[i]] <- list(test = NA, chisq.pvalue = NA, F.pvalue = NA,
                       df = c(NA, length(resid(object))))

  res <- as.data.frame(t(sapply(res, unlist))[, c(4, 5, 1, 3, 2)])

  res[, 1] <- as.integer(res[, 1])
  res[, 2] <- as.integer(res[, 2])
  res <- res[nrow(res):1, ]

  fos <- lapply(o, formula)

  fos <- sapply(fos, function(X){
    paste(X[2], X[3], sep = " ~ ")
  })

  rownames(res) <- rev(fos)

  res
}

**Comment by msalibian** [comment] 2020-10-08 16:37
Thanks or the comment. 

I believe what you may have tried to use `RobStatTM::lmrobLinTest` on an object of class `lmrob`. Since `RobStatTM::lmrobLinTest` is meant to be used with objects returned by lmrobdetMM (which are different from those returned by `robustbase::lmrob`), this is not a bug of `RobStatTM::lmrobLinTest`.

However, the help page for `RobStatTM::lmrobLinTest` incorrectly said that the arguments should be of class `lmrob`. This is now fixed on the documentation, and will be on the CRAN version soon.

As for the potential bug in `robustbase::lmrobLinTest`, I will be in touch by email shortly.

**Closed as completed by msalibian** 2020-10-08 16:37 UTC
